Hash table
XRater/2ndCourse-Java pull request #1
Opened 2017-09-17 20:54 UTC by XRater

2017-09-25 19:30 UTC, yurii-litvinov requested changes
Всё правильно, есть только небольшие замечания. Первая задача зачтена, вторая (про юнит-тесты и комментарии) пусть будет не совсем зачтена, чтобы был повод всё-таки исправить замечания :)

2017-09-25 19:30 UTC, yurii-litvinov commented on HashTable/src/main/java/ru/spbau/mit/kirakosian/KeyValueStringList.java
> +KeyValueStringList {
Название класса пишется по стайлгайду на той же строчке, что и ключевое слово

2017-09-25 19:30 UTC, yurii-litvinov commented on HashTable/src/main/java/ru/spbau/mit/kirakosian/KeyValueStringList.java
> +     * @return size of the list
Лучше без тэга `@return`, а просто `Returns size of the list`. Так при генерации JavaDoc-а комментарий будет сгенерирован не только в детальное описание метода, но и в краткое описание, которое в таблице всех методов класса

2017-09-25 19:30 UTC, yurii-litvinov commented on HashTable/src/main/java/ru/spbau/mit/kirakosian/KeyValueStringList.java
> +            return;
Лучше бросать исключение, например, IllegalArgumentException. Иначе для пользователя может оказаться неожиданно, что он положил null и вроде всё ок, а null не положился

2017-09-25 19:30 UTC, yurii-litvinov commented on HashTable/src/main/java/ru/spbau/mit/kirakosian/KeyValueStringList.java
> +        return false;
Немного копипаст. get же делает ту же работу, только с другой целью, можно было общую функциональность переиспользовать.

2017-09-25 19:30 UTC, yurii-litvinov commented on HashTable/src/main/java/ru/spbau/mit/kirakosian/StringHashMap.java
> +    public int size() {
Тут тоже нужен комментарий

2017-09-25 19:30 UTC, yurii-litvinov commented on HashTable/src/main/java/ru/spbau/mit/kirakosian/StringHashMap.java
> +        data = new KeyValueStringList[data.length];
data.length мог уже вырасти до ужасных размеров, я бы от clear ожидал возврат к INITIAL_SIZE

2017-09-25 19:30 UTC, yurii-litvinov commented on HashTable/src/test/java/ru/spbau/mit/kirakosian/KeyValueStringListTest.java
> +        assertEquals(list.size(), 0);
В assertEquals наоборот, сначала expected, затем actual

2017-09-25 19:30 UTC, yurii-litvinov commented on HashTable/src/main/java/ru/spbau/mit/kirakosian/KeyValueStringList.java
> +package java.ru.spbau.mit.kirakosian;
Не надо называть свои пакеты с java, это обычно означает пакеты из JDK

2017-09-25 20:08 UTC, XRater commented on HashTable/src/main/java/ru/spbau/mit/kirakosian/KeyValueStringList.java
> +        return false;
Я не очень понимаю, как можно объединить именно эти два метода. Можно дать возможность итерироваться по листу, но это лишь удаляет строчки curr = curr.next из всех методов. В остальном переиспользование кода не удается. 

Еще можно создать отдельный метод для поиска (приватный), который делает ровно тоже самое, но возвращает пару вида значение + есть ли элемент, но как мне кажется, такое решение выглядит довольно коряво.

P.S. Тупо вызвать get в contains нельзя, т.к. лист может содержать ключи, значения для которых равны null.

2017-09-26 07:19 UTC, yurii-litvinov commented on HashTable/src/main/java/ru/spbau/mit/kirakosian/KeyValueStringList.java
> +        return false;
Поэтому и "немного" копипаст, и это можно не править :) Два принципиальных способа пофиксить эту проблему --- запретить null-ы (как делает, например, .NET в своих контейнерах, но это не принято в Java) или сделать-таки приватный метод, возвращающий Node (или null), так что contains просто проверял бы результат на null, а get возвращал бы value от результата.

2017-10-21 13:25 UTC, yurii-litvinov approved these changes
Всё правильно, зачтена

2017-10-21 13:25 UTC, yurii-litvinov commented on HashTable/src/main/ru/spbau/mit/kirakosian/KeyValueStringList.java
> +
Две пустые строки подряд не рекомендуются стайлгайдом

2017-10-21 13:25 UTC, yurii-litvinov commented on HashTable/src/main/ru/spbau/mit/kirakosian/KeyValueStringList.java
> +
Перед "}" пустая строка тоже обычно не ставится

2017-10-21 13:25 UTC, yurii-litvinov commented on HashTable/src/test/ru/spbau/mit/kirakosian/KeyValueStringListTest.java
> +        KeyValueStringList list = new KeyValueStringList();
Тут переменная list, в общем-то, не нужна, мы проверили, что конструктор работает --- и всё

2017-10-21 13:56 UTC, merged